version = 1
SPDX-PackageName = "maps-sdk-ios"
SPDX-PackageSupplier = "magiclane-developer@users.noreply.github.com"
SPDX-PackageDownloadLocation = "https://github.com/magiclane/magiclane-maps-sdk-ios"
SPDX-PackageComment = "Get the binary frameworks of the MagicLane Maps SDK for iOS through SPM."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "1995-2025 Magic Lane International B.V. <info@magiclane.com>"
SPDX-License-Identifier = "LicenseRef-MagicLane-Proprietary"
